export interface ThemeDefinition {
  id: string
  name: string
  category: 'dark' | 'light'
  author: string
  description: string
  previewColors: [string, string, string, string] // [bg, accent, text, secondary]
  monacoTheme: {
    base: 'vs-dark' | 'vs'
    inherit: boolean
    rules: { token: string; foreground?: string; background?: string; fontStyle?: string }[]
    colors: Record<string, string>
  }
}

export const VSCODE_THEMES: ThemeDefinition[] = [
  // ── 1. VS Code Dark+ (Default) ─────────────────────────────────────────────
  {
    id: 'vscode-dark',
    name: 'VS Code Dark+ (Default)',
    category: 'dark',
    author: 'Microsoft',
    description: 'The iconic default dark theme of Visual Studio Code',
    previewColors: ['#1e1e1e', '#007acc', '#d4d4d4', '#4ec9b0'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'd4d4d4' },
        { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c586c0' },
        { token: 'keyword.control', foreground: 'c586c0' },
        { token: 'keyword.operator', foreground: 'd4d4d4' },
        { token: 'string', foreground: 'ce9178' },
        { token: 'number', foreground: 'b5cea8' },
        { token: 'type', foreground: '4ec9b0' },
        { token: 'type.identifier', foreground: '4ec9b0' },
        { token: 'function', foreground: 'dcdcaa' },
        { token: 'delimiter', foreground: 'd4d4d4' },
        { token: 'variable.predefined', foreground: '4fc1ff' },
      ],
      colors: {
        'editor.background': '#1e1e1e',
        'editor.foreground': '#d4d4d4',
        'editor.lineHighlightBackground': '#2a2d2e',
        'editor.selectionBackground': '#264f78',
        'editorCursor.foreground': '#aeafad',
        'editorLineNumber.foreground': '#858585',
        'editorLineNumber.activeForeground': '#c6c6c6',
        'editorIndentGuide.background1': '#404040',
        'editorIndentGuide.activeBackground1': '#707070',
        'editorBracketMatch.background': '#0064001a',
        'editorBracketMatch.border': '#888888',
        'editorGutter.background': '#1e1e1e',
      },
    },
  },

  // ── 2. Dracula Official ───────────────────────────────────────────────────
  {
    id: 'dracula',
    name: 'Dracula Official',
    category: 'dark',
    author: 'Zeno Rocha',
    description: 'A dark theme for vampires, featuring vibrant neon pastels',
    previewColors: ['#282a36', '#bd93f9', '#f8f8f2', '#ff79c6'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'f8f8f2' },
        { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ff79c6' },
        { token: 'keyword.control', foreground: 'ff79c6' },
        { token: 'keyword.operator', foreground: 'ff79c6' },
        { token: 'string', foreground: 'f1fa8c' },
        { token: 'number', foreground: 'bd93f9' },
        { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
        { token: 'type.identifier', foreground: '8be9fd' },
        { token: 'function', foreground: '50fa7b' },
        { token: 'delimiter', foreground: 'f8f8f2' },
        { token: 'variable.predefined', foreground: 'ffb86c' },
      ],
      colors: {
        'editor.background': '#282a36',
        'editor.foreground': '#f8f8f2',
        'editor.lineHighlightBackground': '#44475a75',
        'editor.selectionBackground': '#44475a',
        'editorCursor.foreground': '#aeafad',
        'editorLineNumber.foreground': '#6272a4',
        'editorLineNumber.activeForeground': '#f8f8f2',
        'editorIndentGuide.background1': '#ffffff1a',
        'editorIndentGuide.activeBackground1': '#ffffff45',
        'editorBracketMatch.background': '#bd93f930',
        'editorBracketMatch.border': '#bd93f9',
        'editorGutter.background': '#282a36',
      },
    },
  },

  // ── 3. One Dark Pro (Atom) ────────────────────────────────────────────────
  {
    id: 'one-dark-pro',
    name: 'One Dark Pro',
    category: 'dark',
    author: 'Binaryify',
    description: "Atom's iconic One Dark theme, one of the most installed in VS Code",
    previewColors: ['#282c34', '#61afef', '#abb2bf', '#98c379'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'abb2bf' },
        { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c678dd' },
        { token: 'keyword.control', foreground: 'c678dd' },
        { token: 'keyword.operator', foreground: '56b6c2' },
        { token: 'string', foreground: '98c379' },
        { token: 'number', foreground: 'd19a66' },
        { token: 'type', foreground: 'e5c07b' },
        { token: 'type.identifier', foreground: 'e5c07b' },
        { token: 'function', foreground: '61afef' },
        { token: 'delimiter', foreground: 'abb2bf' },
        { token: 'variable.predefined', foreground: 'e06c75' },
      ],
      colors: {
        'editor.background': '#282c34',
        'editor.foreground': '#abb2bf',
        'editor.lineHighlightBackground': '#2c313c',
        'editor.selectionBackground': '#3e4451',
        'editorCursor.foreground': '#528bff',
        'editorLineNumber.foreground': '#4b5263',
        'editorLineNumber.activeForeground': '#abb2bf',
        'editorIndentGuide.background1': '#3b4048',
        'editorIndentGuide.activeBackground1': '#626772',
        'editorBracketMatch.background': '#515a6b',
        'editorBracketMatch.border': '#528bff',
        'editorGutter.background': '#282c34',
      },
    },
  },

  // ── 4. GitHub Dark ────────────────────────────────────────────────────────
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    category: 'dark',
    author: 'GitHub',
    description: 'The standard dark theme from GitHub.com',
    previewColors: ['#0d1117', '#58a6ff', '#e6edf3', '#7ee787'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'e6edf3' },
        { token: 'comment', foreground: '8b949e', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ff7b72' },
        { token: 'keyword.control', foreground: 'ff7b72' },
        { token: 'keyword.operator', foreground: '79c0ff' },
        { token: 'string', foreground: 'a5d6ff' },
        { token: 'number', foreground: '79c0ff' },
        { token: 'type', foreground: 'ffa657' },
        { token: 'type.identifier', foreground: 'ffa657' },
        { token: 'function', foreground: 'd2a8ff' },
        { token: 'delimiter', foreground: '8b949e' },
        { token: 'variable.predefined', foreground: 'ffa657' },
      ],
      colors: {
        'editor.background': '#0d1117',
        'editor.foreground': '#e6edf3',
        'editor.lineHighlightBackground': '#161b22',
        'editor.selectionBackground': '#388bfd33',
        'editorCursor.foreground': '#e6edf3',
        'editorLineNumber.foreground': '#484f58',
        'editorLineNumber.activeForeground': '#e6edf3',
        'editorIndentGuide.background1': '#21262d',
        'editorIndentGuide.activeBackground1': '#30363d',
        'editorBracketMatch.background': '#388bfd25',
        'editorBracketMatch.border': '#388bfd',
        'editorGutter.background': '#0d1117',
      },
    },
  },

  // ── 5. GitHub Dark Dimmed ─────────────────────────────────────────────────
  {
    id: 'github-dark-dimmed',
    name: 'GitHub Dark Dimmed',
    category: 'dark',
    author: 'GitHub',
    description: 'Subtle and comfortable lower-contrast dark palette from GitHub',
    previewColors: ['#22272e', '#539bf5', '#adbac7', '#6cb6ff'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'adbac7' },
        { token: 'comment', foreground: '768390', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'f47067' },
        { token: 'keyword.control', foreground: 'f47067' },
        { token: 'keyword.operator', foreground: '6cb6ff' },
        { token: 'string', foreground: '96d0ff' },
        { token: 'number', foreground: '6cb6ff' },
        { token: 'type', foreground: 'f69d50' },
        { token: 'type.identifier', foreground: 'f69d50' },
        { token: 'function', foreground: 'dcbdfb' },
        { token: 'delimiter', foreground: '768390' },
        { token: 'variable.predefined', foreground: 'f69d50' },
      ],
      colors: {
        'editor.background': '#22272e',
        'editor.foreground': '#adbac7',
        'editor.lineHighlightBackground': '#2d333b',
        'editor.selectionBackground': '#4184e433',
        'editorCursor.foreground': '#adbac7',
        'editorLineNumber.foreground': '#545d68',
        'editorLineNumber.activeForeground': '#adbac7',
        'editorIndentGuide.background1': '#2d333b',
        'editorIndentGuide.activeBackground1': '#444c56',
        'editorBracketMatch.background': '#539bf525',
        'editorBracketMatch.border': '#539bf5',
        'editorGutter.background': '#22272e',
      },
    },
  },

  // ── 6. Monokai Pro ────────────────────────────────────────────────────────
  {
    id: 'monokai-pro',
    name: 'Monokai Pro',
    category: 'dark',
    author: 'Monokai',
    description: 'The beloved developer palette engineered for laser focus',
    previewColors: ['#2d2a2e', '#ffd866', '#fcfcfa', '#ff6188'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'fcfcfa' },
        { token: 'comment', foreground: '727072', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ff6188' },
        { token: 'keyword.control', foreground: 'ff6188' },
        { token: 'keyword.operator', foreground: 'ff6188' },
        { token: 'string', foreground: 'ffd866' },
        { token: 'number', foreground: 'ab9df2' },
        { token: 'type', foreground: '78dce8', fontStyle: 'italic' },
        { token: 'type.identifier', foreground: '78dce8' },
        { token: 'function', foreground: 'a9dc76' },
        { token: 'delimiter', foreground: '939293' },
        { token: 'variable.predefined', foreground: 'fc9867' },
      ],
      colors: {
        'editor.background': '#2d2a2e',
        'editor.foreground': '#fcfcfa',
        'editor.lineHighlightBackground': '#3a373b',
        'editor.selectionBackground': '#403e41',
        'editorCursor.foreground': '#ffd866',
        'editorLineNumber.foreground': '#727072',
        'editorLineNumber.activeForeground': '#fcfcfa',
        'editorIndentGuide.background1': '#403e41',
        'editorIndentGuide.activeBackground1': '#727072',
        'editorBracketMatch.background': '#ffd86630',
        'editorBracketMatch.border': '#ffd866',
        'editorGutter.background': '#2d2a2e',
      },
    },
  },

  // ── 7. Tokyo Night ────────────────────────────────────────────────────────
  {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    category: 'dark',
    author: 'Enkia',
    description: 'Clean, futuristic dark theme inspired by the lights of downtown Tokyo',
    previewColors: ['#1a1b26', '#7aa2f7', '#a9b1d6', '#bb9af7'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'a9b1d6' },
        { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'bb9af7' },
        { token: 'keyword.control', foreground: 'bb9af7' },
        { token: 'keyword.operator', foreground: '89ddff' },
        { token: 'string', foreground: '9ece6a' },
        { token: 'number', foreground: 'ff9e64' },
        { token: 'type', foreground: '2ac3de' },
        { token: 'type.identifier', foreground: '2ac3de' },
        { token: 'function', foreground: '7aa2f7' },
        { token: 'delimiter', foreground: '89ddff' },
        { token: 'variable.predefined', foreground: 'f7768e' },
      ],
      colors: {
        'editor.background': '#1a1b26',
        'editor.foreground': '#a9b1d6',
        'editor.lineHighlightBackground': '#24283b',
        'editor.selectionBackground': '#283457',
        'editorCursor.foreground': '#c0caf5',
        'editorLineNumber.foreground': '#363b54',
        'editorLineNumber.activeForeground': '#737aa2',
        'editorIndentGuide.background1': '#292e42',
        'editorIndentGuide.activeBackground1': '#3b4261',
        'editorBracketMatch.background': '#7aa2f733',
        'editorBracketMatch.border': '#7aa2f7',
        'editorGutter.background': '#1a1b26',
      },
    },
  },

  // ── 8. Catppuccin Mocha ───────────────────────────────────────────────────
  {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    category: 'dark',
    author: 'Catppuccin Org',
    description: 'Soothing warm pastel theme for high productivity and comfort',
    previewColors: ['#1e1e2e', '#cba6f7', '#cdd6f4', '#f38ba8'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'cdd6f4' },
        { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'cba6f7' },
        { token: 'keyword.control', foreground: 'cba6f7' },
        { token: 'keyword.operator', foreground: '89dceb' },
        { token: 'string', foreground: 'a6e3a1' },
        { token: 'number', foreground: 'fab387' },
        { token: 'type', foreground: 'f9e2af' },
        { token: 'type.identifier', foreground: 'f9e2af' },
        { token: 'function', foreground: '89b4fa' },
        { token: 'delimiter', foreground: '9399b2' },
        { token: 'variable.predefined', foreground: 'f38ba8' },
      ],
      colors: {
        'editor.background': '#1e1e2e',
        'editor.foreground': '#cdd6f4',
        'editor.lineHighlightBackground': '#31324466',
        'editor.selectionBackground': '#45475a',
        'editorCursor.foreground': '#f5e0dc',
        'editorLineNumber.foreground': '#585b70',
        'editorLineNumber.activeForeground': '#cdd6f4',
        'editorIndentGuide.background1': '#313244',
        'editorIndentGuide.activeBackground1': '#45475a',
        'editorBracketMatch.background': '#cba6f733',
        'editorBracketMatch.border': '#cba6f7',
        'editorGutter.background': '#1e1e2e',
      },
    },
  },

  // ── 9. Nord ───────────────────────────────────────────────────────────────
  {
    id: 'nord',
    name: 'Nord',
    category: 'dark',
    author: 'Arctic Ice Studio',
    description: 'An arctic, north-bluish clean and elegant color palette',
    previewColors: ['#2e3440', '#88c0d0', '#d8dee9', '#81a1c1'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'd8dee9' },
        { token: 'comment', foreground: '4c566a', fontStyle: 'italic' },
        { token: 'keyword', foreground: '81a1c1' },
        { token: 'keyword.control', foreground: '81a1c1' },
        { token: 'keyword.operator', foreground: '81a1c1' },
        { token: 'string', foreground: 'a3be8c' },
        { token: 'number', foreground: 'b48ead' },
        { token: 'type', foreground: '8fbcbb' },
        { token: 'type.identifier', foreground: '8fbcbb' },
        { token: 'function', foreground: '88c0d0' },
        { token: 'delimiter', foreground: 'd8dee9' },
        { token: 'variable.predefined', foreground: 'bf616a' },
      ],
      colors: {
        'editor.background': '#2e3440',
        'editor.foreground': '#d8dee9',
        'editor.lineHighlightBackground': '#3b4252',
        'editor.selectionBackground': '#434c5e',
        'editorCursor.foreground': '#d8dee9',
        'editorLineNumber.foreground': '#4c566a',
        'editorLineNumber.activeForeground': '#d8dee9',
        'editorIndentGuide.background1': '#3b4252',
        'editorIndentGuide.activeBackground1': '#4c566a',
        'editorBracketMatch.background': '#88c0d033',
        'editorBracketMatch.border': '#88c0d0',
        'editorGutter.background': '#2e3440',
      },
    },
  },

  // ── 10. Night Owl ─────────────────────────────────────────────────────────
  {
    id: 'night-owl',
    name: 'Night Owl',
    category: 'dark',
    author: 'Sarah Drasner',
    description: 'A theme for late-night coders with vibrant colors and rich dark navy',
    previewColors: ['#011627', '#82aaff', '#d6deeb', '#c792ea'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'd6deeb' },
        { token: 'comment', foreground: '637777', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'c792ea' },
        { token: 'keyword.control', foreground: 'c792ea' },
        { token: 'keyword.operator', foreground: '7fdbca' },
        { token: 'string', foreground: 'ecc48d' },
        { token: 'number', foreground: 'f78c6c' },
        { token: 'type', foreground: 'ffcb8b' },
        { token: 'type.identifier', foreground: 'ffcb8b' },
        { token: 'function', foreground: '82aaff' },
        { token: 'delimiter', foreground: 'd6deeb' },
        { token: 'variable.predefined', foreground: 'addb67' },
      ],
      colors: {
        'editor.background': '#011627',
        'editor.foreground': '#d6deeb',
        'editor.lineHighlightBackground': '#0b2942',
        'editor.selectionBackground': '#1d3b53',
        'editorCursor.foreground': '#7e57c2',
        'editorLineNumber.foreground': '#4b6479',
        'editorLineNumber.activeForeground': '#c5e4fd',
        'editorIndentGuide.background1': '#0b2942',
        'editorIndentGuide.activeBackground1': '#1d3b53',
        'editorBracketMatch.background': '#82aaff33',
        'editorBracketMatch.border': '#82aaff',
        'editorGutter.background': '#011627',
      },
    },
  },

  // ── 11. SynthWave '84 (Cyberpunk) ──────────────────────────────────────────
  {
    id: 'synthwave-84',
    name: "SynthWave '84",
    category: 'dark',
    author: 'Robb Owen',
    description: 'Retro 80s neon glowing aesthetic inspired by modern synthwave art',
    previewColors: ['#262335', '#ff7edb', '#f92aad', '#36f9f6'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'f92aad' },
        { token: 'comment', foreground: '614d85', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'fede5d' },
        { token: 'keyword.control', foreground: 'fede5d' },
        { token: 'keyword.operator', foreground: 'fe4450' },
        { token: 'string', foreground: 'ff7edb' },
        { token: 'number', foreground: 'f97e72' },
        { token: 'type', foreground: 'fe4450' },
        { token: 'type.identifier', foreground: 'fe4450' },
        { token: 'function', foreground: '36f9f6' },
        { token: 'delimiter', foreground: 'f92aad' },
        { token: 'variable.predefined', foreground: 'ff7edb' },
      ],
      colors: {
        'editor.background': '#262335',
        'editor.foreground': '#f92aad',
        'editor.lineHighlightBackground': '#34294f55',
        'editor.selectionBackground': '#ffffff22',
        'editorCursor.foreground': '#fe4450',
        'editorLineNumber.foreground': '#544670',
        'editorLineNumber.activeForeground': '#ff7edb',
        'editorIndentGuide.background1': '#34294f',
        'editorIndentGuide.activeBackground1': '#493774',
        'editorBracketMatch.background': '#36f9f633',
        'editorBracketMatch.border': '#36f9f6',
        'editorGutter.background': '#262335',
      },
    },
  },

  // ── 12. Cobalt2 ───────────────────────────────────────────────────────────
  {
    id: 'cobalt2',
    name: 'Cobalt2',
    category: 'dark',
    author: 'Wes Bos',
    description: 'Wes Bos legendary vibrant deep navy blue with sunshine yellow accents',
    previewColors: ['#193549', '#ffc600', '#ffffff', '#0088ff'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: 'ffffff' },
        { token: 'comment', foreground: '0088ff', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'ff9d00' },
        { token: 'keyword.control', foreground: 'ff9d00' },
        { token: 'keyword.operator', foreground: '0088ff' },
        { token: 'string', foreground: '3ad900' },
        { token: 'number', foreground: 'ff628c' },
        { token: 'type', foreground: '80ffbb' },
        { token: 'type.identifier', foreground: '80ffbb' },
        { token: 'function', foreground: 'ffc600' },
        { token: 'delimiter', foreground: 'ffffff' },
        { token: 'variable.predefined', foreground: 'ffc600' },
      ],
      colors: {
        'editor.background': '#193549',
        'editor.foreground': '#ffffff',
        'editor.lineHighlightBackground': '#1f4662',
        'editor.selectionBackground': '#005088',
        'editorCursor.foreground': '#ffc600',
        'editorLineNumber.foreground': '#386588',
        'editorLineNumber.activeForeground': '#ffc600',
        'editorIndentGuide.background1': '#1f4662',
        'editorIndentGuide.activeBackground1': '#0088ff55',
        'editorBracketMatch.background': '#ffc60033',
        'editorBracketMatch.border': '#ffc600',
        'editorGutter.background': '#193549',
      },
    },
  },

  // ── 13. Solarized Dark ────────────────────────────────────────────────────
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    category: 'dark',
    author: 'Ethan Schoonover',
    description: 'Precision engineered scientifically tuned low-contrast color palette',
    previewColors: ['#002b36', '#268bd2', '#839496', '#2aa198'],
    monacoTheme: {
      base: 'vs-dark',
      inherit: true,
      rules: [
        { token: '', foreground: '839496' },
        { token: 'comment', foreground: '586e75', fontStyle: 'italic' },
        { token: 'keyword', foreground: '859900' },
        { token: 'keyword.control', foreground: '859900' },
        { token: 'keyword.operator', foreground: '859900' },
        { token: 'string', foreground: '2aa198' },
        { token: 'number', foreground: 'd33682' },
        { token: 'type', foreground: 'b58900' },
        { token: 'type.identifier', foreground: 'b58900' },
        { token: 'function', foreground: '268bd2' },
        { token: 'delimiter', foreground: '839496' },
        { token: 'variable.predefined', foreground: 'cb4b16' },
      ],
      colors: {
        'editor.background': '#002b36',
        'editor.foreground': '#839496',
        'editor.lineHighlightBackground': '#073642',
        'editor.selectionBackground': '#073642',
        'editorCursor.foreground': '#d30102',
        'editorLineNumber.foreground': '#586e75',
        'editorLineNumber.activeForeground': '#93a1a1',
        'editorIndentGuide.background1': '#073642',
        'editorIndentGuide.activeBackground1': '#586e75',
        'editorBracketMatch.background': '#268bd233',
        'editorBracketMatch.border': '#268bd2',
        'editorGutter.background': '#002b36',
      },
    },
  },

  // ── 14. GitHub Light ──────────────────────────────────────────────────────
  {
    id: 'github-light',
    name: 'GitHub Light',
    category: 'light',
    author: 'GitHub',
    description: 'Crisp, clean default light theme from GitHub',
    previewColors: ['#ffffff', '#0969da', '#24292f', '#1a7f37'],
    monacoTheme: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: '', foreground: '24292f' },
        { token: 'comment', foreground: '6e7781', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'cf222e' },
        { token: 'keyword.control', foreground: 'cf222e' },
        { token: 'keyword.operator', foreground: '0550ae' },
        { token: 'string', foreground: '0a3069' },
        { token: 'number', foreground: '0550ae' },
        { token: 'type', foreground: '953800' },
        { token: 'type.identifier', foreground: '953800' },
        { token: 'function', foreground: '8250df' },
        { token: 'delimiter', foreground: '24292f' },
        { token: 'variable.predefined', foreground: '953800' },
      ],
      colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#24292f',
        'editor.lineHighlightBackground': '#f6f8fa',
        'editor.selectionBackground': '#b6e3ff',
        'editorCursor.foreground': '#24292f',
        'editorLineNumber.foreground': '#8c959f',
        'editorLineNumber.activeForeground': '#24292f',
        'editorIndentGuide.background1': '#eaeef2',
        'editorIndentGuide.activeBackground1': '#d0d7de',
        'editorBracketMatch.background': '#0969da20',
        'editorBracketMatch.border': '#0969da',
        'editorGutter.background': '#ffffff',
      },
    },
  },

  // ── 15. VS Code Light+ (Default Light) ────────────────────────────────────
  {
    id: 'vscode-light',
    name: 'VS Code Light+ (Default)',
    category: 'light',
    author: 'Microsoft',
    description: 'The standard default light theme of Visual Studio Code',
    previewColors: ['#ffffff', '#007acc', '#000000', '#001080'],
    monacoTheme: {
      base: 'vs',
      inherit: true,
      rules: [
        { token: '', foreground: '000000' },
        { token: 'comment', foreground: '008000', fontStyle: 'italic' },
        { token: 'keyword', foreground: 'af00db' },
        { token: 'keyword.control', foreground: 'af00db' },
        { token: 'keyword.operator', foreground: '000000' },
        { token: 'string', foreground: 'a31515' },
        { token: 'number', foreground: '098658' },
        { token: 'type', foreground: '267f99' },
        { token: 'type.identifier', foreground: '267f99' },
        { token: 'function', foreground: '795e26' },
        { token: 'delimiter', foreground: '000000' },
        { token: 'variable.predefined', foreground: '001080' },
      ],
      colors: {
        'editor.background': '#ffffff',
        'editor.foreground': '#000000',
        'editor.lineHighlightBackground': '#f3f3f3',
        'editor.selectionBackground': '#add6ff',
        'editorCursor.foreground': '#000000',
        'editorLineNumber.foreground': '#237893',
        'editorLineNumber.activeForeground': '#0b216f',
        'editorIndentGuide.background1': '#d3d3d3',
        'editorIndentGuide.activeBackground1': '#939393',
        'editorBracketMatch.background': '#007acc25',
        'editorBracketMatch.border': '#007acc',
        'editorGutter.background': '#ffffff',
      },
    },
  },
]

export interface UIThemeColors {
  bgApp: string
  bgHeader: string
  bgSidebar: string
  bgActivity: string
  bgPanel: string
  bgCard: string
  bgInput: string
  bgHover: string
  border: string
  borderSubtle: string
  textBase: string
  textMuted: string
  textDim: string
  accent: string
  accentHover: string
  accentSubtle: string
  accentBorder: string
  red: string
  green: string
  yellow: string
}

export const THEME_UI_PALETTES: Record<string, UIThemeColors> = {
  'vscode-dark': {
    bgApp: '#1e1e1e',
    bgHeader: '#252526',
    bgSidebar: '#252526',
    bgActivity: '#333333',
    bgPanel: '#1e1e1e',
    bgCard: '#2d2d2d',
    bgInput: '#3c3c3c',
    bgHover: 'rgba(255, 255, 255, 0.08)',
    border: '#3c3c3c',
    borderSubtle: '#474747',
    textBase: '#d4d4d4',
    textMuted: '#858585',
    textDim: '#6e6e6e',
    accent: '#007acc',
    accentHover: '#0062a3',
    accentSubtle: 'rgba(0, 122, 204, 0.18)',
    accentBorder: 'rgba(0, 122, 204, 0.45)',
    red: '#f14c4c',
    green: '#89d185',
    yellow: '#cca700',
  },
  'dracula': {
    bgApp: '#282a36',
    bgHeader: '#21222c',
    bgSidebar: '#21222c',
    bgActivity: '#191a21',
    bgPanel: '#282a36',
    bgCard: '#343746',
    bgInput: '#1e1f29',
    bgHover: 'rgba(255, 255, 255, 0.07)',
    border: '#44475a',
    borderSubtle: '#6272a4',
    textBase: '#f8f8f2',
    textMuted: '#8be9fd',
    textDim: '#6272a4',
    accent: '#bd93f9',
    accentHover: '#ff79c6',
    accentSubtle: 'rgba(189, 147, 249, 0.18)',
    accentBorder: 'rgba(189, 147, 249, 0.45)',
    red: '#ff5555',
    green: '#50fa7b',
    yellow: '#f1fa8c',
  },
  'one-dark-pro': {
    bgApp: '#282c34',
    bgHeader: '#21252b',
    bgSidebar: '#21252b',
    bgActivity: '#1b1d23',
    bgPanel: '#282c34',
    bgCard: '#2c313a',
    bgInput: '#1e2227',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#3b4048',
    borderSubtle: '#4b5263',
    textBase: '#abb2bf',
    textMuted: '#7f848e',
    textDim: '#5c6370',
    accent: '#61afef',
    accentHover: '#528bff',
    accentSubtle: 'rgba(97, 175, 239, 0.18)',
    accentBorder: 'rgba(97, 175, 239, 0.4)',
    red: '#e06c75',
    green: '#98c379',
    yellow: '#e5c07b',
  },
  'github-dark': {
    bgApp: '#0d1117',
    bgHeader: '#161b22',
    bgSidebar: '#161b22',
    bgActivity: '#161b22',
    bgPanel: '#0d1117',
    bgCard: '#1c2128',
    bgInput: '#0d1117',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#21262d',
    borderSubtle: '#30363d',
    textBase: '#e6edf3',
    textMuted: '#7d8590',
    textDim: '#484f58',
    accent: '#7c3aed',
    accentHover: '#6d28d9',
    accentSubtle: 'rgba(124, 58, 237, 0.15)',
    accentBorder: 'rgba(124, 58, 237, 0.4)',
    red: '#f85149',
    green: '#3fb950',
    yellow: '#d29922',
  },
  'github-dark-dimmed': {
    bgApp: '#22272e',
    bgHeader: '#2d333b',
    bgSidebar: '#2d333b',
    bgActivity: '#1c2128',
    bgPanel: '#22272e',
    bgCard: '#2d333b',
    bgInput: '#1c2128',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#444c56',
    borderSubtle: '#545d68',
    textBase: '#adbac7',
    textMuted: '#768390',
    textDim: '#545d68',
    accent: '#539bf5',
    accentHover: '#4184e4',
    accentSubtle: 'rgba(83, 155, 245, 0.18)',
    accentBorder: 'rgba(83, 155, 245, 0.4)',
    red: '#f47067',
    green: '#57ab5a',
    yellow: '#c69026',
  },
  'monokai-pro': {
    bgApp: '#2d2a2e',
    bgHeader: '#221f22',
    bgSidebar: '#221f22',
    bgActivity: '#1e1c1e',
    bgPanel: '#2d2a2e',
    bgCard: '#3a373b',
    bgInput: '#19181a',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#403e41',
    borderSubtle: '#5a575b',
    textBase: '#fcfcfa',
    textMuted: '#939293',
    textDim: '#727072',
    accent: '#ffd866',
    accentHover: '#fc9867',
    accentSubtle: 'rgba(255, 216, 102, 0.18)',
    accentBorder: 'rgba(255, 216, 102, 0.45)',
    red: '#ff6188',
    green: '#a9dc76',
    yellow: '#ffd866',
  },
  'tokyo-night': {
    bgApp: '#1a1b26',
    bgHeader: '#16161e',
    bgSidebar: '#16161e',
    bgActivity: '#13141c',
    bgPanel: '#1a1b26',
    bgCard: '#24283b',
    bgInput: '#13141c',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#292e42',
    borderSubtle: '#414868',
    textBase: '#c0caf5',
    textMuted: '#7aa2f7',
    textDim: '#565f89',
    accent: '#7aa2f7',
    accentHover: '#bb9af7',
    accentSubtle: 'rgba(122, 162, 247, 0.18)',
    accentBorder: 'rgba(122, 162, 247, 0.4)',
    red: '#f7768e',
    green: '#9ece6a',
    yellow: '#e0af68',
  },
  'catppuccin-mocha': {
    bgApp: '#1e1e2e',
    bgHeader: '#181825',
    bgSidebar: '#181825',
    bgActivity: '#11111b',
    bgPanel: '#1e1e2e',
    bgCard: '#313244',
    bgInput: '#11111b',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#313244',
    borderSubtle: '#45475a',
    textBase: '#cdd6f4',
    textMuted: '#a6adc8',
    textDim: '#6c7086',
    accent: '#cba6f7',
    accentHover: '#f5c2e7',
    accentSubtle: 'rgba(203, 166, 247, 0.18)',
    accentBorder: 'rgba(203, 166, 247, 0.4)',
    red: '#f38ba8',
    green: '#a6e3a1',
    yellow: '#f9e2af',
  },
  'nord': {
    bgApp: '#2e3440',
    bgHeader: '#272c36',
    bgSidebar: '#272c36',
    bgActivity: '#232730',
    bgPanel: '#2e3440',
    bgCard: '#3b4252',
    bgInput: '#242933',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#434c5e',
    borderSubtle: '#4c566a',
    textBase: '#d8dee9',
    textMuted: '#88c0d0',
    textDim: '#4c566a',
    accent: '#88c0d0',
    accentHover: '#81a1c1',
    accentSubtle: 'rgba(136, 192, 208, 0.18)',
    accentBorder: 'rgba(136, 192, 208, 0.4)',
    red: '#bf616a',
    green: '#a3be8c',
    yellow: '#ebcb8b',
  },
  'night-owl': {
    bgApp: '#011627',
    bgHeader: '#01111d',
    bgSidebar: '#01111d',
    bgActivity: '#000c14',
    bgPanel: '#011627',
    bgCard: '#0b253a',
    bgInput: '#00101c',
    bgHover: 'rgba(255, 255, 255, 0.06)',
    border: '#1d3b53',
    borderSubtle: '#2a4e6c',
    textBase: '#d6deeb',
    textMuted: '#82aaff',
    textDim: '#5f7e97',
    accent: '#82aaff',
    accentHover: '#c792ea',
    accentSubtle: 'rgba(130, 170, 255, 0.18)',
    accentBorder: 'rgba(130, 170, 255, 0.4)',
    red: '#ef5350',
    green: '#22da6e',
    yellow: '#addb67',
  },
  'synthwave-84': {
    bgApp: '#262335',
    bgHeader: '#1f1c2b',
    bgSidebar: '#1f1c2b',
    bgActivity: '#171520',
    bgPanel: '#262335',
    bgCard: '#34294f',
    bgInput: '#191724',
    bgHover: 'rgba(255, 255, 255, 0.08)',
    border: '#34294f',
    borderSubtle: '#493b6e',
    textBase: '#f92aad',
    textMuted: '#ff7edb',
    textDim: '#848bbd',
    accent: '#fe4450',
    accentHover: '#ff7edb',
    accentSubtle: 'rgba(254, 68, 80, 0.22)',
    accentBorder: 'rgba(254, 68, 80, 0.5)',
    red: '#fe4450',
    green: '#72f1b8',
    yellow: '#fede5d',
  },
  'cobalt2': {
    bgApp: '#193549',
    bgHeader: '#122738',
    bgSidebar: '#122738',
    bgActivity: '#0d1d2a',
    bgPanel: '#193549',
    bgCard: '#1f415b',
    bgInput: '#0f2231',
    bgHover: 'rgba(255, 255, 255, 0.08)',
    border: '#204a6e',
    borderSubtle: '#2e6390',
    textBase: '#ffffff',
    textMuted: '#0088ff',
    textDim: '#005096',
    accent: '#ffc600',
    accentHover: '#ff9d00',
    accentSubtle: 'rgba(255, 198, 0, 0.22)',
    accentBorder: 'rgba(255, 198, 0, 0.5)',
    red: '#ff0000',
    green: '#3ad900',
    yellow: '#ffc600',
  },
  'solarized-dark': {
    bgApp: '#002b36',
    bgHeader: '#073642',
    bgSidebar: '#073642',
    bgActivity: '#00212b',
    bgPanel: '#002b36',
    bgCard: '#0a4150',
    bgInput: '#001f27',
    bgHover: 'rgba(255, 255, 255, 0.07)',
    border: '#0e4a58',
    borderSubtle: '#1a5d6e',
    textBase: '#93a1a1',
    textMuted: '#839496',
    textDim: '#586e75',
    accent: '#268bd2',
    accentHover: '#2aa198',
    accentSubtle: 'rgba(38, 139, 210, 0.22)',
    accentBorder: 'rgba(38, 139, 210, 0.45)',
    red: '#dc322f',
    green: '#859900',
    yellow: '#b58900',
  },
  'github-light': {
    bgApp: '#ffffff',
    bgHeader: '#f6f8fa',
    bgSidebar: '#f6f8fa',
    bgActivity: '#eaedf1',
    bgPanel: '#ffffff',
    bgCard: '#f6f8fa',
    bgInput: '#ffffff',
    bgHover: 'rgba(0, 0, 0, 0.05)',
    border: '#d0d7de',
    borderSubtle: '#e1e4e8',
    textBase: '#1f2328',
    textMuted: '#656d76',
    textDim: '#8c959f',
    accent: '#0969da',
    accentHover: '#0860ca',
    accentSubtle: 'rgba(9, 105, 218, 0.12)',
    accentBorder: 'rgba(9, 105, 218, 0.35)',
    red: '#cf222e',
    green: '#1a7f37',
    yellow: '#9a6700',
  },
  'vscode-light': {
    bgApp: '#ffffff',
    bgHeader: '#f3f3f3',
    bgSidebar: '#f3f3f3',
    bgActivity: '#e8e8e8',
    bgPanel: '#ffffff',
    bgCard: '#f8f8f8',
    bgInput: '#ffffff',
    bgHover: 'rgba(0, 0, 0, 0.05)',
    border: '#e5e5e5',
    borderSubtle: '#d0d0d0',
    textBase: '#333333',
    textMuted: '#616161',
    textDim: '#888888',
    accent: '#007acc',
    accentHover: '#0062a3',
    accentSubtle: 'rgba(0, 122, 204, 0.12)',
    accentBorder: 'rgba(0, 122, 204, 0.35)',
    red: '#cd3131',
    green: '#008000',
    yellow: '#795e26',
  },
}

export const DEFAULT_THEME_ID = 'vscode-dark'

export function getThemeById(themeId: string): ThemeDefinition {
  return VSCODE_THEMES.find(t => t.id === themeId) || VSCODE_THEMES[0]
}

export function registerMonacoThemes(monacoInstance: any) {
  if (!monacoInstance?.editor?.defineTheme) return
  for (const theme of VSCODE_THEMES) {
    try {
      monacoInstance.editor.defineTheme(theme.id, theme.monacoTheme as any)
    } catch (e) {
      console.warn(`Failed to register theme ${theme.id}:`, e)
    }
  }
}

export function getThemeUIColors(themeId: string): UIThemeColors {
  return THEME_UI_PALETTES[themeId] || THEME_UI_PALETTES['github-dark']
}

export function applyThemeToDocument(themeId: string) {
  const theme = getThemeById(themeId)
  const colors = getThemeUIColors(themeId)
  const root = document.documentElement

  root.setAttribute('data-theme', themeId)
  root.setAttribute('data-theme-category', theme.category)

  root.style.setProperty('--bg-app', colors.bgApp)
  root.style.setProperty('--bg-header', colors.bgHeader)
  root.style.setProperty('--bg-sidebar', colors.bgSidebar)
  root.style.setProperty('--bg-activity', colors.bgActivity)
  root.style.setProperty('--bg-panel', colors.bgPanel)
  root.style.setProperty('--bg-card', colors.bgCard)
  root.style.setProperty('--bg-input', colors.bgInput)
  root.style.setProperty('--bg-hover', colors.bgHover)
  root.style.setProperty('--border', colors.border)
  root.style.setProperty('--border-subtle', colors.borderSubtle)
  root.style.setProperty('--text-base', colors.textBase)
  root.style.setProperty('--text-muted', colors.textMuted)
  root.style.setProperty('--text-dim', colors.textDim)
  root.style.setProperty('--accent', colors.accent)
  root.style.setProperty('--accent-hover', colors.accentHover)
  root.style.setProperty('--accent-subtle', colors.accentSubtle)
  root.style.setProperty('--accent-border', colors.accentBorder)
  root.style.setProperty('--red', colors.red)
  root.style.setProperty('--green', colors.green)
  root.style.setProperty('--yellow', colors.yellow)
}
